version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pharmtrace
      POSTGRES_USER: pharmtrace
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmtrace"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./apps/api
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://pharmtrace:${POSTGRES_PASSWORD}@postgres:5432/pharmtrace"

  web:
    build: ./apps/web
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: "http://api:4000"

volumes:
  pgdata: {}
